### ISSUE TITLE
Implement voting system.

### ISSUE THREAD

**Issue by dhopcs** [blackmesadev/black-mesa#12]
Allow for a user with a certain configurable permission level to start a vote to mute/kick/ban (all of which can be disabled/enabled) of a duration (a max duration can be configured). It must receive a configurable number of "upvotes" before being passed (possibly also allow for a percentage of active users).

**Comment by RGBCube** [comment]
something like 
\>\>votekick \<member\> [reason]
![example image](https://autumn.revolt.chat/attachments/x8OTILWSOaRxl2uZv0xY3rcJ8aF7S-CZWQAlOyvJ-T/image.png)

**Comment by dhopcs** [comment]
Added in `modules/voting`.
