### ISSUE TITLE
`processMuted` does not correctly return a mute on user rejoin.

### ISSUE THREAD

**Issue by lurr** [blackmesadev/black-mesa#17]
Yeah I dunno. Might just suffice to replace all the logic there with a call to `db.GetMute()` so the logic is the same everywhere.

**Comment by lurr** [comment]
Bug somewhere in https://github.com/blackmesadev/black-mesa/blob/c13c220febf59d7d2e16c8a640ac84f31b0476d5/modules/automod/users.go#L83-L113

**Comment by dhopcs** [comment]
> Yeah I dunno. Might just suffice to replace all the logic there with a call to `db.GetMute()` so the logic is the same everywhere.

That would make sense to do this here for sure, good solution.
