### ISSUE TITLE
time thingy on >>search go bad

### ISSUE THREAD

**Issue by soupcantrolling** [blackmesadev/black-mesa#21]
fuck
![image](https://user-images.githubusercontent.com/104684447/166108768-b91bb9d4-e8ed-42e2-b7fb-d4658cd2df6b.png)

**Comment by dhopcs** [comment]
Fixed in https://github.com/blackmesadev/black-mesa/commit/bf72219e6feba42fe41a7c1c00fd95ded98de06d
