### ISSUE TITLE
Allow for priviledged users to view expired strikes

### ISSUE THREAD

**Issue by lurr** [blackmesadev/black-mesa#28]
This will likely require changes to how `actionExpiryGoroutine` in `discord/discord.go` functions; instead of removing actions from the database they should persist.

Similarly, `db.GetPunishments` will require a change; likely just a boolean stating whether to filter out expired items or not.
Two options for how to format the command, either `>>search -a <ids[]>` or `>>searchall <ids[]>`.

**Comment by dhopcs** [comment]
Closing as Black Mesa has been rewritten, this is now a feature in the form of `deepsearch` and `search` being distinctive
