### ISSUE TITLE
Bot gives incorrect information if the striked user is already muted.

### ISSUE THREAD

**Issue by astralship-system** [blackmesadev/black-mesa#36]
When an user is striked and the automod is configured to escalate the punishment with a mute with them being already muted prior, the bot will send an incorrect message. The bot informs that it has failed to strike the aforementioned user, even though the error is a failed mute.

![image](https://user-images.githubusercontent.com/19747005/180984510-0f334fa6-120b-431a-be10-9f5cdcc1eb56.png)
![image](https://user-images.githubusercontent.com/19747005/180985054-6e1886af-d793-40c5-8cec-0154e4810fbc.png)

**Comment by dhopcs** [comment]
Closing as Black Mesa has been rewritten.
