### ISSUE TITLE
Introduce a command for modifying existing entries.

### ISSUE THREAD

**Issue by astralship-system** [blackmesadev/black-mesa#37]
As of now, it is possible to update a reason with an existing mute or ban for another user, but not the strike/warn.
I suggest there should be a new command to handle all 3 cases, something like:
{prefix}modify {uuid} {length} {reason}
for example.

**Comment by dhopcs** [comment]
Closing as Black Mesa has been rewritten, this is now a feature in the form of the commands
`reason`
`duration`
and soon `update`
