### ISSUE TITLE
Log who deleted the message.

### ISSUE THREAD

**Issue by astralship-system** [blackmesadev/black-mesa#38]
Currently, the only way to see who deleted a certain message is by looking through the audit log, which is not ideal since the audit log entries automatically disappear after some time, as well as being unreliable if there's tens if not hundreds of messages deletes in the given automod log channel. An ideal approach would be providing this information with-in the message delete log itself to make things more clear.

**Comment by dhopcs** [comment]
Closing as Black Mesa has been rewritten.
