### ISSUE TITLE
Check ID length before parsing punishment users

### ISSUE THREAD

**Issue by RGBCube** [blackmesadev/black-mesa#5]
the bot currently just checks if it is a number or not, before applying the punishment, the bot could check if its a valid id, if it isnt it could re add it back to the start of the reason with a space.

![image](https://cdn.discordapp.com/attachments/871378795993661532/946429731505594388/IMG_5072.png)

**Comment by dhopcs** [comment]
Non issue - Black Mesa command parsing will treat anything before the duration as an ID in this context, this is user error in this case and will not be investigated further
