### ISSUE TITLE
Strike/Mutes don't show when they expire

### ISSUE THREAD

**Issue by KosovoToday** [blackmesadev/black-mesa#6]
I got muted/striked for sending a photo of Russia's ministry of defense emails and passwords, i got the dm from Black Mesa but the strikes didn't show an expiration date. I also got duplicates of the same message by Black Mesa.
![Screenshot_20220227-141117](https://user-images.githubusercontent.com/97382064/155902079-2f426866-6dff-405b-a075-b2bf44d39c65.png)
-KosovoToday

**Comment by dhopcs** [comment]
Looks like during strike escalation instead of sending a new embed containing the new punishment, it sends the send embed of the strike.
