### ISSUE TITLE
Block the .gift TLD

### ISSUE THREAD

**Issue by tired6488** [blackmesadev/black-mesa#7]
Since the .gift tld seems to primarily be used for Discord nitro scams or Discord nitro, adding an option to block all .gift urls with discord.gift whitelisted would be good.

**Comment by dhopcs** [comment]
Will create a separate automod module for this that will be added to with all new scams that get released, some sort of public database that others can request to add scam domains to would be a good idea I think.

**Comment by RGBCube** [comment]
> Will create a separate automod module for this that will be added to with all new scams that get released, some sort of public database that others can request to add scam domains to would be a good idea I think.

https://github.com/jagrosh/Vortex/blob/master/lists/referral_domains.txt maybe?

**Comment by RGBCube** [comment]
oh, also https://phish.sinking.yachts/docs

**Comment by dhopcs** [comment]
> > Will create a separate automod module for this that will be added to with all new scams that get released, some sort of public database that others can request to add scam domains to would be a good idea I think.
> 
> https://github.com/jagrosh/Vortex/blob/master/lists/referral_domains.txt maybe?

Good find, could reference and cache this file internally, would like to allow for people to upload files that will be referenced for each server with "recommended" files too, which would include this one.

**Comment by dhopcs** [comment]
Untrustworthy module fixes this issue, more to be added to it in the future but the framework for this is there.
